# Generated by Django 4.1.4 on 2023-01-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
