# Generated by Django 4.1.4 on 2023-01-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='views',
        ),
    ]
