# Generated by Django 4.1.4 on 2023-01-29 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
