# Generated by Django 4.1.4 on 2023-01-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_tag_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(related_name='tag_set', to='forum.question'),
        ),
    ]
