# Generated by Django 4.1.4 on 2023-01-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_tag_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(blank=True, to='forum.question'),
        ),
    ]
