# Generated by Django 4.1.4 on 2023-02-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_tag_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='create_time',
        ),
    ]
